### ISSUE TITLE
Make popups less ugly by tweaking CSS

### ISSUE THREAD

**Issue by kenz-gelsoft** [kenz-gelsoft/gecko-dev#80]
Splitted from https://github.com/kenz-gelsoft/gecko-dev/issues/77

We can't create complex shape popups with alpha channel reasonably.

Work around ugly visual by changing styles for them.

**Comment by kenz-gelsoft** [comment]
popup.css
```css
  @media (-moz-platform: linux) or (-moz-platform: windows) {
    /* To account for the box-shadow below */
    --panel-shadow-margin: 4px;
  }
```
